[package]
name = "castify"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
actix-web-actors = "4.3.1"
dotenv = "0.15.0"
reqwest = { version = "0.12.15", features = ["json"] }
serde_json = "1.0.140"
